package ex_exception

fun main()
{
    val str = "abcd"
    val num = str.toInt()

    println(num)
}